### ISSUE TITLE
Can't send email

### ISSUE THREAD

**Issue by tech62** [byceps/byceps#8]
```
`11:49:06 default: byceps.services.email.service.send_email('Server<server@mydomain>', ['me@mydomain.'], 'test, bitte bestätige deine E-Mail-Adresse', 'Hallo test,\n\nbitte bestätige deine E-Mail-Adresse, indem du diese URL ab...) (4f37c2ad-838d-48a2-aac0-13a36de6f173)
Delivery of message <163316814607.26645.4651114900449846356@smtp.myserver> failed.
11:49:06 Traceback (most recent call last):
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/manager/util.py", line 50, in __enter__
    transport = pool.transports.get(False)
  File "/usr/lib/python3.7/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/byceps/venv/lib/python3.7/site-packages/rq/worker.py", line 1031, in perform_job
    rv = job.perform()
  File "/root/byceps/venv/lib/python3.7/site-packages/rq/job.py", line 749, in perform
    self._result = self._execute()
  File "/root/byceps/venv/lib/python3.7/site-packages/rq/job.py", line 772, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/root/byceps/byceps/services/email/service.py", line 164, in send_email
    email.send(sender, recipients, subject, body)
  File "/root/byceps/byceps/email.py", line 74, in send
    mailer.send(message)
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/__init__.py", line 149, in send
    result = self.manager.deliver(message)
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/manager/immediate.py", line 41, in deliver
    with self.transport() as transport:
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/manager/util.py", line 57, in __enter__
    transport.startup()
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/transport/smtp.py", line 50, in startup
    self.connect_to_server()
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/transport/smtp.py", line 84, in connect_to_server
    connection.starttls(self.keyfile, self.certfile)
  File "/usr/lib/python3.7/smtplib.py", line 771, in starttls
    server_hostname=self._host)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 846, in _create
    owner=self, session=self._session,
ValueError: server_hostname cannot be an empty string or start with a leading dot.
Traceback (most recent call last):
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/manager/util.py", line 50, in __enter__
    transport = pool.transports.get(False)
  File "/usr/lib/python3.7/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/byceps/venv/lib/python3.7/site-packages/rq/worker.py", line 1031, in perform_job
    rv = job.perform()
  File "/root/byceps/venv/lib/python3.7/site-packages/rq/job.py", line 749, in perform
    self._result = self._execute()
  File "/root/byceps/venv/lib/python3.7/site-packages/rq/job.py", line 772, in _execute
    result = self.func(*self.args, **self.kwargs)
  File "/root/byceps/byceps/services/email/service.py", line 164, in send_email
    email.send(sender, recipients, subject, body)
  File "/root/byceps/byceps/email.py", line 74, in send
    mailer.send(message)
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/__init__.py", line 149, in send
    result = self.manager.deliver(message)
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/manager/immediate.py", line 41, in deliver
    with self.transport() as transport:
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/manager/util.py", line 57, in __enter__
    transport.startup()
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/transport/smtp.py", line 50, in startup
    self.connect_to_server()
  File "/root/byceps/venv/lib/python3.7/site-packages/marrow/mailer/transport/smtp.py", line 84, in connect_to_server
    connection.starttls(self.keyfile, self.certfile)
  File "/usr/lib/python3.7/smtplib.py", line 771, in starttls
    server_hostname=self._host)
  File "/usr/lib/python3.7/ssl.py", line 412, in wrap_socket
    session=session
  File "/usr/lib/python3.7/ssl.py", line 846, in _create
    owner=self, session=self._session,
ValueError: server_hostname cannot be an empty string or start with a leading dot.
`
```
```
My conf : 
`
SESSION_COOKIE_SECURE = True

REDIS_URL = 'redis://127.0.0.1:6379/0'

RQ_DASHBOARD_ENABLED = True

APP_MODE = 'site'
SITE_ID = 'intra'

MAIL_DEBUG =  False
MAIL_DEFAULT_SENDER = 'servermail@myserver.com'
MAIL_SUPPRESS_SEND = False

#DEBUG_TOOLBAR_ENABLED = True
#STYLE_GUIDE_ENABLED = True

MAIL_TRANSPORT = 'smtp'
MAIL_SERVER  = 'smtp.myserver.com'
MAIL_PORT = 25
MAIL_USERNAME = 'myusername@myserver.com'
MAIL_PASSWORD = 'topsecretpassword'
MAIL_USE_TLS = False
MAIL_USE_SSL = False
`
```

**Comment by homeworkprod** [comment]
This is an issue with at least Python 3.7 and 3.8: https://bugs.python.org/issue36094
Unfortunately, work towards fixing it seems to have stalled.

For the gory details, https://github.com/marrow/mailer/issues/83 bundles a lot of links, correction attempts, discussion, and reasoning why the place to fix it is in Python itself.

As a temporary fix I suggest to change the line at https://github.com/marrow/mailer/blob/4.0.3/marrow/mailer/transport/smtp.py#L74 as follows (or the similar line above it in case you want to use SSL):
```diff
- connection = SMTP(local_hostname=self.local_hostname, timeout=self.timeout)
+ connection = SMTP(host=self.host, local_hostname=self.local_hostname, timeout=self.timeout)
```
even though that might have some minor drawbacks.

Since the issue does not appear with a *local* SMTP server, another workaround could be setting up a local SMTP server that forwards to the external one.

**Comment by homeworkprod** [comment]
Since you stated on Discord that the change worked for you to get email via an external SMTP server going, I'll close here.
